title: Desplegar
description:
theme: just-the-docs

url: https://desplegar.info

aux_links:
  Rizoma.pe: https://rizoma.pe

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-G12W09S1N3
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

callouts:
warning:
title: OJO
color: blue
